export const KEGIATAN_LIST_REQUEST = "KEGIATAN_LIST_REQUEST";
export const KEGIATAN_LIST_SUCCESS = "KEGIATAN_LIST_SUCCESS";
export const KEGIATAN_LIST_FAIL = "KEGIATAN_LIST_FAIL";

export const KEGIATAN_DELETE_REQUEST = "KEGIATAN_DELETE_REQUEST";
export const KEGIATAN_DELETE_SUCCESS = "KEGIATAN_DELETE_SUCCESS";
export const KEGIATAN_DELETE_FAIL = "KEGIATAN_DELETE_FAIL";
export const KEGIATAN_DELETE_RESET = "KEGIATAN_DELETE_RESET";

export const KEGIATAN_CREATE_REQUEST = "KEGIATAN_CREATE_REQUEST";
export const KEGIATAN_CREATE_SUCCESS = "KEGIATAN_CREATE_SUCCESS";
export const KEGIATAN_CREATE_FAIL = "KEGIATAN_CREATE_FAIL";
export const KEGIATAN_CREATE_RESET = "KEGIATAN_CREATE_RESET";
