export const STUDI_LIST_REQUEST = "STUDI_LIST_REQUEST";
export const STUDI_LIST_SUCCESS = "STUDI_LIST_SUCCESS";
export const STUDI_LIST_FAIL = "STUDI_LIST_FAIL";

export const STUDI_LISTDROPDOWN_REQUEST = "STUDI_LISTDROPDOWN_REQUEST";
export const STUDI_LISTDROPDOWN_SUCCESS = "STUDI_LISTDROPDOWN_SUCCESS";
export const STUDI_LISTDROPDOWN_FAIL = "STUDI_LISTDROPDOWN_FAIL";

export const STUDI_DELETE_REQUEST = "STUDI_DELETE_REQUEST";
export const STUDI_DELETE_SUCCESS = "STUDI_DELETE_SUCCESS";
export const STUDI_DELETE_FAIL = "STUDI_DELETE_FAIL";
export const STUDI_DELETE_RESET = "STUDI_DELETE_RESET";

export const STUDI_CREATE_REQUEST = "STUDI_CREATE_REQUEST";
export const STUDI_CREATE_SUCCESS = "STUDI_CREATE_SUCCESS";
export const STUDI_CREATE_FAIL = "STUDI_CREATE_FAIL";
export const STUDI_CREATE_RESET = "STUDI_CREATE_RESET";

export const STUDI_DETAILS_REQUEST = "STUDI_DETAILS_REQUEST";
export const STUDI_DETAILS_SUCCESS = "STUDI_DETAILS_SUCCESS";
export const STUDI_DETAILS_FAIL = "STUDI_DETAILS_FAIL";
export const STUDI_DETAILS_RESET = "STUDI_DETAILS_RESET";

export const STUDI_UPDATE_REQUEST = "STUDI_UPDATE_REQUEST";
export const STUDI_UPDATE_SUCCESS = "STUDI_UPDATE_SUCCESS";
export const STUDI_UPDATE_FAIL = "STUDI_UPDATE_FAIL";
export const STUDI_UPDATE_RESET = "STUDI_UPDATE_RESET";
