export const MAHASISWA_LIST_REQUEST = "MAHASISWA_LIST_REQUEST";
export const MAHASISWA_LIST_SUCCESS = "MAHASISWA_LIST_SUCCESS";
export const MAHASISWA_LIST_FAIL = "MAHASISWA_LIST_FAIL";

export const MAHASISWA_DELETE_REQUEST = "MAHASISWA_DELETE_REQUEST";
export const MAHASISWA_DELETE_SUCCESS = "MAHASISWA_DELETE_SUCCESS";
export const MAHASISWA_DELETE_FAIL = "MAHASISWA_DELETE_FAIL";
export const MAHASISWA_DELETE_RESET = "MAHASISWA_DELETE_RESET";

export const MAHASISWA_CREATE_REQUEST = "MAHASISWA_CREATE_REQUEST";
export const MAHASISWA_CREATE_SUCCESS = "MAHASISWA_CREATE_SUCCESS";
export const MAHASISWA_CREATE_FAIL = "MAHASISWA_CREATE_FAIL";
export const MAHASISWA_CREATE_RESET = "MAHASISWA_CREATE_RESET";

export const MAHASISWA_DETAILS_REQUEST = "MAHASISWA_DETAILS_REQUEST";
export const MAHASISWA_DETAILS_SUCCESS = "MAHASISWA_DETAILS_SUCCESS";
export const MAHASISWA_DETAILS_FAIL = "MAHASISWA_DETAILS_FAIL";
export const MAHASISWA_DETAILS_RESET = "MAHASISWA_DETAILS_RESET";

export const MAHASISWA_UPDATE_REQUEST = "MAHASISWA_UPDATE_REQUEST";
export const MAHASISWA_UPDATE_SUCCESS = "MAHASISWA_UPDATE_SUCCESS";
export const MAHASISWA_UPDATE_FAIL = "MAHASISWA_UPDATE_FAIL";
export const MAHASISWA_UPDATE_RESET = "MAHASISWA_UPDATE_RESET";
